settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: short.rep.us.kg # unique identifier
    name: short.rep.us.kg
    description: '短链服务' # default=empty
    url: 'https://short.rep.us.kg/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: docker-hub.rep.us.kg
    name: dockerhub-proxy.rep.us.kg
    description: 'docker 镜像站'
    url: 'https://dockerhub-proxy.rep.us.kg'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: githubproxy.rep.us.kg
    name: githubproxy.rep.us.kg
    url: 'https://githubproxy.rep.us.kg/'
    description: 'github 镜像站'
    method: GET
    expectStatus: 200
